### PR TITLE
Indeterminate checkbox

### PR DESCRIPTION
**Pull request by appledora**
Tried to solve the issue raised at #14 . 
Added indeterminate checkboxes in `index.html` , updated `script.js` and added markdown checkboxes in the `README.md`

### CODE REVIEW

**Review by bryanbraun — CHANGES_REQUESTED** [review]
Thanks for taking on this issue!

I left a few requests in the comments—if you can address those we'll get it merged. 👍

**Review by appledora — COMMENTED** [review]
Addressed all the review changes, hopefully :3

**Review by appledora — COMMENTED** [review]
minor changes

**Review by bryanbraun — APPROVED** [review]
Looks great! Thanks for your patience. :)

**Pull request merged**
